import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/header'
import Footer from '@/components/footer'
import GoogleAnalytics from '@/components/GoogleAnalytics'
import CookieBanner from '@/components/CookieBanner'


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Trainotel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='scroll-smooth' lang="en">
      <GoogleAnalytics GA_MEASUREMENT_ID='G-RXKFJCM0P8' />
      <body className={inter.className}>
        <Header />
        {children}
        <CookieBanner/>
        <Footer />
      </body>
    </html>
  )
}
